### ISSUE TITLE
naming principle

### ISSUE THREAD

**Issue by jsimbrig** [alliedvision/examples#1]
when cloning examples
a directory named examples is created.
That's not really a good hint on the hard disk as to what that is.
The cloner has to rename it to AVT_Examples or whatever.

I would suggest to name the project folders so that you can see on the cloner's harddisk what it has cloned from where and from who !

**Comment by mrkschnk** [comment]
Good point. I suggest you use the command `git clone https://github.com/alliedvision/examples.git AV_Examples` or whatever you prefer.

Hope this answers your comment.
